build: fix build_and_deploy to view logs even on failure

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -95,12 +95,17 @@ jobs:
           docker compose up migrations --exit-code-from migrations
 
           # Run without migrations (avoid exit code 0)
-          docker compose up --detach \
-            --no-deps --wait --wait-timeout 60 \
-            central-db central central-proxy s3 api
-
-          # View logs afterwards
-          docker compose logs api
+          # Also run within if block to capture logs if failure
+          if docker compose up --detach \
+              --no-deps --wait --wait-timeout 60 \
+              central-db central central-proxy s3 api
+          then
+              docker compose logs api
+          else
+              echo "Application not healthy after 1m0s. Exiting."
+              docker compose logs api
+              exit 1
+          fi
 
   smoke-test-frontend:
     runs-on: ubuntu-latest
